import { chromium, devices } from "@playwright/test";
const out = "/private/tmp/claude-501/-Users-rehan-Documents-Drip/bb5feee4-6208-4b54-84d3-20ddd51e7068/scratchpad/shots";
const [path, name] = [process.argv[2] ?? "/", process.argv[3] ?? "home"];
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices["iPhone 14 Pro"], viewport: { width: 393, height: 852 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push("pageerror: " + e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push("console: " + m.text()); });
await page.goto("http://localhost:3100" + path, { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/${name}.png` });
console.log("errors:", errors.length ? errors : "none");
await browser.close();
