import { z } from "zod";

/**
 * Per-session visual identity. Generated by the planner from the SUBJECT's own
 * world. All values become CSS custom properties on the feed root
 * (lib/theme/cssVars.ts); components consume ONLY the variables.
 */
export const Hex = z.string().regex(/^#(?:[0-9a-fA-F]{3}){1,2}$/, "hex color");

/**
 * Curated, self-hosted font list (next/font/google, loaded in lib/theme/fonts.ts).
 * The AI picks from these; it cannot invent fonts. Keys are the values the
 * planner emits; each maps to a CSS variable exported by fonts.ts.
 */
export const DISPLAY_FONTS = [
  "space-grotesk",       // grotesk, technical
  "bricolage-grotesque", // grotesk with character
  "syne",                // wide, art-school
  "unbounded",           // heavy, poster
  "fraunces",            // soft editorial serif
  "playfair-display",    // high-contrast editorial serif
  "instrument-serif",    // elegant, narrow serif
  "zilla-slab",          // slab
  "dm-sans",             // clean geometric humanist
  "manrope",             // rounded-geometric
  "nunito",              // rounded, friendly
] as const;

export const BODY_FONTS = [
  "dm-sans", "ibm-plex-sans", "manrope", "nunito", "source-serif-4",
  "fraunces", "zilla-slab", "space-grotesk", "bricolage-grotesque",
] as const;

export const MONO_FONTS = ["jetbrains-mono", "ibm-plex-mono", "fira-code"] as const;

export const ALL_FONTS = Array.from(new Set([...DISPLAY_FONTS, ...BODY_FONTS, ...MONO_FONTS]));
export type FontKey = (typeof ALL_FONTS)[number];

export const TEXTURES = ["none", "grain", "grid", "scanlines", "dots"] as const;
export const MOTIONS = ["snappy", "fluid", "mechanical", "bouncy"] as const;

export const ThemeSchema = z.object({
  name: z.string().max(40),                     // "terminal noir", "field notes"
  mood: z.string().max(120),                    // one-line art direction, must justify itself from the subject
  bg: z.object({
    base: Hex,
    gradientTo: Hex.optional(),
    texture: z.enum(TEXTURES),
  }),
  ink: z.object({ primary: Hex, secondary: Hex }),
  accent: Hex,                                  // exactly ONE accent color
  accentAlt: Hex.optional(),                    // only for correct/incorrect states
  display: z.enum(DISPLAY_FONTS),
  body: z.enum(BODY_FONTS),
  mono: z.enum(MONO_FONTS),
  motion: z.enum(MOTIONS),
  signature: z.string().max(160),               // ONE distinctive device, appears on hooks + checkpoints
  signatureKind: z.enum([
    "hex-addresses",     // section numbers rendered as hex addresses
    "water-lines",       // accent underlines drawn like water levels
    "cursor-blink",      // cursor blink on hook headlines
    "stamp",             // rubber-stamp eyebrow badge
    "ticker",            // scrolling ticker strip under headline
    "ruled-notes",       // ruled paper lines behind hooks
    "waveform",          // audio waveform bar under headline
    "constellation",     // dotted constellation behind headline
    "brackets",          // heavy typographic brackets framing headline
    "underline-sweep",   // accent underline sweeps in
  ]).default("underline-sweep"),
});
export type Theme = z.infer<typeof ThemeSchema>;
